### ISSUE TITLE
Solc v0.8.14

### ISSUE THREAD

**Issue by roynalnaruto** [nikitastupin/solc#3]
gm @nikitastupin . Solidity v0.8.14 has been released, could you manually run the build-and-publish CI flow for this version? We can then proceed to update svm-builds and include this version in foundry.

**Comment by nikitastupin** [comment]
https://github.com/nikitastupin/solc/commit/67d5ed7bbb3d426da15df323325e96ab46835400 - done! Thanks for reminding!
