### ISSUE TITLE
Is there any 0.4.x version?

### ISSUE THREAD

**Issue by paranoid1996** [nikitastupin/solc#5]
Hi , I have to use bin of 0.4.x version
Is there any 0.4.x version

**Comment by nikitastupin** [comment]
Hey @paranoid1996,

Unfortunately, I experienced some issues compiling 0.4.x versions.

I'd appreciate and add them if you share how to compile them.

**Comment by paranoid1996** [comment]
Sorry, I also experienced some issues compiling 0.4.x versions on my arm machine, but it not works.
Thank you for your reply

**Comment by paranoid1996** [comment]
Btw, are 0.5.4-0.5.8 and 0.5.12-0.5.13 versions alse cant compile?

**Comment by nikitastupin** [comment]
That's a good question. I'm not sure 🤔 Maybe I just forgot to compile them

**Comment by paranoid1996** [comment]
hh, well, These versions have helped me a lot
Thanks
